### ISSUE TITLE
Change the docker image visibility to public

### ISSUE THREAD

**Issue by ebrahimebrahim** [KitwareMedical/lungair-desktop-application#47]
Want to give public read permission for [the lung_air_model_deploy package](https://github.com/KitwareMedical/lungair-desktop-application/pkgs/container/lungair-desktop-application%2Flung_air_model_deploy) following [these instructions](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#configuring-visibility-of-container-images-for-an-organization)

See also: https://github.com/KitwareMedical/lungair-desktop-application/pull/41#issuecomment-1273655883

From @Leengit:

> when I select "change visibility", the "Public" option is grayed out and includes the message "Setting is disabled by organization administrators."  ("Internal" (to all people within KitwareMedical) is also grayed out, with the same explanatory message.)  The only allowed option is "Private", which is already selected, and which appears to allow granting of permission to individuals within KitwareMedical.

@jcfr We may need to adjust some permission at the KitwareMedical org level to achieve this

**Comment by jcfr** [comment]
@ebrahimebrahim and I just discussed the availability of public package in the KitwareMedical GitHub organization.

It turns out the feature is disabled by default:

![image](https://user-images.githubusercontent.com/219043/196547864-de6d5256-f527-44be-81ff-098c8073ae91.png)

Enabling the feature have some cost implications.

In a nutshell, there is a cost associated with both storage and data transfer.
* https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages
* https://github.com/pricing/calculator?feature=packages
* https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage

**Comment by jcfr** [comment]
Archiving the docker image in an alternative registry may be sensible.

Some available options:
* https://hub.docker.com/
* https://quay.io/

Since we already have a `kitwaremedical` organization on dockerhub, we should be able to creating an additional repository. Note that there are also limit (e.g `100 pulls per 6 hours`), see details [here](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/).

Considering that switching between registry is relatively easy, starting with a new repository on docker hub may be reasonable.

Lastly, leveraging the registry provided by `https://gitlab.kitware.com` could also be an option. 

All of that said, I suggest to first
1. optimize the image (as suggested by @ebrahimebrahim )
2. leverage cloud resources offered to open-source projects

**Comment by Leengit** [comment]
What are you thoughts on these?  I am thinking that we go with \# 2 rather than the two \#1s.

_Optimize the image:_
1. The base docker image `nvcr.io/nvidia/pytorch:22.09-py3` is used by `monai-deploy` to create a docker image with our MONAI deployable package. We could guess at which subset of functionality from `nvcr.io/nvidia/pytorch:22.09-py3` is actually needed and build our own smaller image as a base.  Even if we cut 18 GiB image by a factor of 10 that's still about 2 GiB, which could add up in download charges.
2. Instead we could have the user directly invoke `monai-deploy package` as part of the `lungair-desktop-application` build process.  The user would thus be downloading the base docker image from `nvcr.io` and then be building our deployed docker image, rather than downloading the latter from our repository.  By making use of the download from `nvcr.io` we leverage that they will be updating images in the upcoming months and years.
3. Alternatively, we could try to describe (the relevant subset of) `nvcr.io/nvidia/pytorch:22.09-py3` and the additions from `monai-deploy package` via a `Dockerfile` that instructs how to build the final docker image on the user's system.  While describing the base image might not be too hard -- the `Dockerfile` might already be available somewhere -- mimicking the functionality of `monai-deploy package` via a `Dockerfile` might be less straightforward.

_Leverage cloud resources:_
1. We don't want to pay for this ... though [here](https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages) I am seeing "GitHub Packages usage is free for public packages", which is a bit confusing.  Regardless, docker hub or `gitlab.kitware.com` look safer.

**Comment by ebrahimebrahim** [comment]
I agree that (2) sounds best. This way we separate ourselves from having to offer any docker image ourselves and pass the responsibility up the chain. And it sounds less complicated than (3). And it leaves us with a nice complete readme that we can point to, a nice way to wrap up the monai deploy investigation.

**Comment by jcfr** [comment]
> as part of the lungair-desktop-application build process

Ditto. Since independently of the chosen approach, `docker` seems to be a hard requirement, moving forward with (2) may be sensible


> build process integration

Here are some hints & suggested next steps:

* Delete [lungair-desktop-application](https://github.com/KitwareMedical/lungair-desktop-application/pkgs/container/lungair-desktop-application) package from the GitHub registry
* Delete [lung_air_model_deploy](https://github.com/KitwareMedical/lungair-desktop-application/pkgs/container/lungair-desktop-application%2Flung_air_model_deploy) package from the GitHub registry
* Create folder `Applications/LungSegmentationMONAIApp` (or `Modules/Scripted/LungSegmentationModel`
  * add `README.md`
    * describe how to train the model (e.g referencing relevant ipynb notebooks, ...)
    * describe how to perform inference (either locally by create a virtual env, or using docker after building the relevant image)
  * move [useful-requirements.txt](https://github.com/KitwareMedical/lungair-desktop-application/blob/af84ff7813971463805f0621c65107c69ca2f7e7/useful-requirements.txt) and rename to `requirements.txt`
  * add `Dockerfile`
  * move `deploy_app.py` and relevant files
  * Copy [FindDocker.cmake](https://github.com/bioinfo-pf-curie/geniac/blob/devel/cmake/FindDocker.cmake)
  * Add `CMakeLists.txt` with `find_package(Docker REQUIRED)` as well as `execute_process()` to build the image.
* Add `SuperBuild/External_LungSegmentationMONAIApp.cmake` (or `External_LungSegmentationModel.cmake` ?)
* Add `LungSegmentationMONAIApp` as a dependency to the LungAir [here](https://github.com/KitwareMedical/lungair-desktop-application/blob/af84ff7813971463805f0621c65107c69ca2f7e7/CMakeLists.txt#L46-L48)

  * this external project will build 
*

**Comment by jcfr** [comment]
> distribution

Here are some hints & suggested next steps:

* Revisit handling of the model distribution as details in https://github.com/KitwareMedical/lungair-desktop-application/pull/41#discussion_r935909468

* Save the generated docker image in an archive using [docker save](https://docs.docker.com/engine/reference/commandline/save/).
   * this could be the last step associated with the `SuperBuild/External_LungSegmentationMONAIApp.cmake` external project
   * Publish the image as a release asset
   * Download the image at runtime and use [docker load](https://docs.docker.com/engine/reference/commandline/load/) to make it available.
   * Consider passing the path to the model while running the docker image. This will help reduce the size of the docker image and is consistent with the "local deploy" use case.

**Comment by ebrahimebrahim** [comment]
@Leengit Since you are going with (2) should we close this issue?

Are you now able to do the readme update indicated in #46 ?

**Comment by Leengit** [comment]
Yes, we should close this issue.  I am addressing Issue #46 with Pull Request #62.
